<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DATACOL-2020</name>
   <tag></tag>
   <elementGuidId>fab19d0e-800f-4598-9c1c-f5b8c73f0fe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='90440500972173337_orig']/tbody/tr[8]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:apex.navigation.dialog('\u002Fords\u002Fhalo\u002Fr\u002Fhalopv800\u002Fview-edit-record?p119_master_id=2020\u0026clear=RP,119\u0026session=17274320227432\u0026cs=3mPgMTINf9jcbMiQ7EwD4KjQFKRUNlqfh02Yi3GtlwDKwaIpOVlAfk4P2DlUg3Ku17fmAq4eljYjNvBxBdNL_ww\u0026dialogCs=Q1ZMmGLgnR6JPdBFeGMxUCWw0Blv-_0nYE-T9b9cYHQlkdGxYzY2S5Drj3Hu_F1Zz4I-m4EZbIhNo3zpuAbbUQ',{title:'View\u002Fedit record',height:'800',width:'1200',maxWidth:'95\u0025',modal:true,dialog:null},'t-Dialog-page--standard '+'',apex.jQuery('#records'));</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DATACOL-2020</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;90440500972173337_orig&quot;)/tbody[1]/tr[8]/td[@class=&quot;u-tL&quot;]/a[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='90440500972173337_orig']/tbody/tr[8]/td[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DATACOL-2020')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[33]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[32]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[34]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data collection Record'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DATACOL-2020']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:apex.navigation.dialog('\u002Fords\u002Fhalo\u002Fr\u002Fhalopv800\u002Fview-edit-record?p119_master_id=2020\u0026clear=RP,119\u0026session=17274320227432\u0026cs=3mPgMTINf9jcbMiQ7EwD4KjQFKRUNlqfh02Yi3GtlwDKwaIpOVlAfk4P2DlUg3Ku17fmAq4eljYjNvBxBdNL_ww\u0026dialogCs=Q1ZMmGLgnR6JPdBFeGMxUCWw0Blv-_0nYE-T9b9cYHQlkdGxYzY2S5Drj3Hu_F1Zz4I-m4EZbIhNo3zpuAbbUQ',{title:'View\u002Fedit record',height:'800',width:'1200',maxWidth:'95\u0025',modal:true,dialog:null},'t-Dialog-page--standard '+'',apex.jQuery('#records'));&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/a</value>
   </webElementXpaths>
</WebElementEntity>
