<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>23551-Case Handling - Solicated Drug</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>6452f60c-900e-4695-bb14-14efaf5bf793</testSuiteGuid>
   <testCaseLink>
      <guid>03376ef4-6753-48bd-9929-e15616c3c531</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Error/23551 - Case Handling - Solicited Drug</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bff2f6d-7765-4240-b083-a44a483e3451</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61264cea-3e07-4a4b-853d-8791de0b61f5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32ecbcd2-8678-4b1e-aebd-97253327aa9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Error/23549 - Case Handling - Clinical Drug</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20529967-1b46-4b28-b3f9-05ba8a3f7282</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a70bc16-180a-4115-babd-c8658eeed9a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b600c7d-428c-4784-a3ad-ee393b28b143</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Error/23548 - Case Handling - Clinical Device</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35ab3395-d316-4e04-9197-14755a93c8a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afaaff98-d38a-4281-803c-5a5198e27874</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3634618d-0aed-494a-aebe-d09762f7bbe9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Error/23550 - Case Handling - Post Marketing Device</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7554f375-3854-41f4-8d2a-0de05a7b25fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d88f66b-08eb-49f0-b69d-d809fe6d0623</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9f8ee38-5156-4e52-9786-79f7166dcdf1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Error/23554 - Submission - Clinical Drug</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1443fb3c-8c83-49ba-ae6b-ab81095c1e3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>507146c7-72a3-48ac-bfeb-f4cfde7f15a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>da67ae6a-3e89-4242-ab2d-bfe57cac910b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Error/23555 - Submission - Post Marketing Device</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c032159-752d-41ae-91e4-249fd42533c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>929c5c27-f7f9-4834-b0ec-c2a290fabb54</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56a7b434-5897-4aed-a1ec-1d1618adde2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Error/23556 - Submission - Solicited Drug</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e09fbe05-777b-47d6-8d76-8a71346c8f2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31670ba8-a1a1-4b6f-bd0a-f16e95704478</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24dddfde-0688-48c0-b0d9-81f2dd9a5398</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Error/23557 - Submission - Spontaneous Drug</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c88d4fef-3204-46ca-96e9-56dd1ce3765b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2864b989-afd9-4989-a703-f5e2704a9952</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90703952-e35a-4448-9367-4aad6a99391c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Error/23553 - Submission - Clinical Device</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11745039-b47c-4e32-8815-e49a5ed660ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b8b4a55-cd29-4c1e-b1bf-d8e501f7b861</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
