<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>23579-Configure properties of scheduled process record with basic task scheduler page</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>116da904-f7c8-4acf-94ea-03b59b75c974</testSuiteGuid>
   <testCaseLink>
      <guid>653159f9-0e50-4327-98a2-6698685eead4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/23579-Configure properties of scheduled process record with basic task scheduler page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5010b0e-6d7f-4b83-b4ac-1f22ce2c5133</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cb304e5-6ba0-45cf-b40c-908eb049d911</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fd27975-be81-42bb-bfba-863cff203758</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c92159ce-ef77-417f-ae87-5a80194c794c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
