<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>23725 - Configure Overriding of Task Completion Date</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c3c7a346-5c3b-4ffb-a8e5-02b8d8e0d048</testSuiteGuid>
   <testCaseLink>
      <guid>e912ede0-283b-4e66-af9b-c1fc528db26b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/23725 - Configure Overriding of Task Completion Date</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0d9f51d-1ef6-40a5-93fe-4565c6212c1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dd34ce4-c07a-4680-bd3f-435d8972263e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24cef10a-4fb1-4b50-95ba-e737acf14519</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a33f5c8e-1749-46e2-ad42-5ab11c234b90</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
