<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>23856-User not allowed to access unauthorized page by manual manipulation of URLs</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2dfced09-5380-4b5b-90d6-09efedda43db</testSuiteGuid>
   <testCaseLink>
      <guid>252b3f1d-8f77-41ca-bd93-addb94d31df4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Error/23856-User not allowed to access unauthorized page by manual manipulation of URLs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd471ee5-fbea-4c16-9914-65e6a0f627c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fc42636-9857-4abf-ad10-6167a6cb66f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71decf4d-011e-44a5-9096-1c67905f1720</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd26324a-1139-4d2a-b2ed-72056b1d74b8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
